stages:
  - publish
  - deploy

variables:
  DOCKER_IMAGE: "dulno-panel"
  DOCKER_STATIC_IMAGE: "dulno-panel-static"
  KUBERNETES_RESOURCE: "deployment/dulno-panel-deployment"

publish:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:latest .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker buildx build -t $DOCKER_REGISTRY/$DOCKER_STATIC_IMAGE:latest -f nginx/Dockerfile .
    - docker push $DOCKER_REGISTRY/$DOCKER_STATIC_IMAGE:latest
  only:
    - master

deploy_panel:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  dependencies:
    - publish
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBERNETES_CONFIGURATION" > ~/.kube/config
  script:
    - kubectl rollout restart $KUBERNETES_RESOURCE
  only:
    - master

deploy_nginx:
  stage: deploy
  trigger:
    project: $NGINX_PIPELINE_PROJECT
    branch: $NGINX_PIPELINE_BRANCH
  only:
    - master